"use client";

import type { PredictionResult } from "../types";
import { AlertCircle, CheckCircle2, RotateCcw } from "lucide-react";

interface Props {
  result: PredictionResult;
  onReset: () => void;
}

export default function ResultCard({ result, onReset }: Props) {
  const isDiabetes = result.class === 1;
  const confidencePct = (result.confidence * 100).toFixed(1);
  const diabetesProbPct = (result.probability_diabetes * 100).toFixed(1);

  const circumference = 2 * Math.PI * 52; // r=52
  const filled = result.confidence * circumference;

  return (
    <div className="result-container">
      {/* Card header */}
      <div className="card-header">
        <h2 className="card-title">Assessment Result</h2>
        <p className="card-description">
          Based on the health metrics you provided.
        </p>
      </div>

      {/* Status badge */}
      <div
        className={`result-status ${
          isDiabetes ? "result-status--danger" : "result-status--safe"
        }`}
      >
        <span className="result-status-icon">
          {isDiabetes ? (
            <AlertCircle size={20} strokeWidth={2.5} />
          ) : (
            <CheckCircle2 size={20} strokeWidth={2.5} />
          )}
        </span>
        <span className="result-status-label">{result.prediction}</span>
      </div>

      {/* Confidence ring */}
      <div className="confidence-section">
        <div className="confidence-ring-wrap">
          <svg viewBox="0 0 120 120" width="140" height="140">
            <circle
              cx="60"
              cy="60"
              r="52"
              className="confidence-ring-track"
            />
            <circle
              cx="60"
              cy="60"
              r="52"
              className={`confidence-ring-fill ${
                isDiabetes
                  ? "confidence-ring-fill--danger"
                  : "confidence-ring-fill--safe"
              }`}
              strokeDasharray={`${filled} ${circumference}`}
              transform="rotate(-90 60 60)"
            />
          </svg>
          <div className="confidence-ring-center">
            <span className="confidence-pct">{confidencePct}%</span>
            <span className="confidence-label">Confidence</span>
          </div>
        </div>
      </div>

      {/* Metric cards */}
      <div className="metrics-grid">
        <div className="metric">
          <p className="metric-label">Class</p>
          <p className="metric-value">{result.class}</p>
        </div>
        <div className="metric">
          <p className="metric-label">Diabetes Prob.</p>
          <p className="metric-value">{diabetesProbPct}%</p>
        </div>
      </div>

      {/* Disclaimer */}
      <p className="result-disclaimer">
        This assessment is generated by a machine-learning model and should not
        replace professional medical advice. Please consult your physician.
      </p>

      {/* New prediction button */}
      <button
        type="button"
        onClick={onReset}
        className="btn-primary"
        id="new-prediction"
        style={{ width: "100%", display: "flex", alignItems: "center", justifyContent: "center", gap: "8px" }}
      >
        <RotateCcw size={18} />
        New Prediction
      </button>
    </div>
  );
}
